name: First workflow

on: push

jobs:
    First_job:
        runs-on : ubuntu-latest
        steps:
            - name: copy repo
              uses: actions/checkout@v3
            - name: First job
              run: echo "welcome to github actions"
            - name: list files
              run: ls
            - name: view
              run: cat README.txt 
              

            
    
   